version: '2'
services:
  headless-client:
    build: dependencies/headless-client
    links:
      - redis
      - postgres
    environment: &environment
      - TOKEN_APP_SEED=embrace crack admit trip speed rural armed scout project lock else learn
      - TOKEN_APP_USERNAME=DharmaAssistant
      - TOKEN_APP_NAME=Dharma Assistant
      - TOKEN_APP_AVATAR=attachments/square_logo.png
      - OZ_ROOT_PATH=https://oz.dharma.io
      - DAPP_ROOT_PATH=https://dharma-loan-confirmation.firebaseapp.com
      - REDIS_URL=redis://h:rlcMWNrxXgqS0xM8aWCYuE0R@redis:6379
      - DATABASE_URL=postgres://token:va5uOdJBqu2dZ1@postgres:5432/token
      - LOG_LEVEL=INFO
      - ENABLE_LOG_TIMESTAMPS=0
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - WEB3_PROVIDER=http://geth:8545
      - DEFAULT_ACCOUNT=0xac7f7b63d1d6e311695693235eb3262f60fea079
      - LOAN_CONTRACT_ADDR=0x29BEDe679f82cfE352795d375d0BFe51FFbb05F1
    volumes:
      - ./config/docker.yml:/usr/src/headless-client/config.yml
      - ./attachments:/usr/src/headless-client/attachments
  bot:
    build: .
    ports:
      - 80:80
      - 443:443
    links:
      - redis
      - postgres
    environment: *environment
    volumes:
      - ./config/docker.yml:/usr/src/bot/config.yml
      - ./contracts:/usr/src/bot/src/contracts
      - ./src:/usr/src/bot/src
      - ./ssl:/usr/src/bot/src/ssl
      - ./attestations:/usr/src/bot/attestations
  redis:
    build: dependencies/redis
    ports:
      - 6379
  postgres:
    image: postgres:9.6
    ports:
      - 15432
    environment:
      - POSTGRES_PASSWORD=va5uOdJBqu2dZ1
      - POSTGRES_USER=token
      - POSTGRES_DB=token
  geth:
    image: ethereum/client-go
    command: --testnet --keystore=/root/payouts/keystore --fast --cache=512 --networkid=3 --rpc --rpcaddr 'geth' --rpcapi eth,net,web3,personal,admin,miner --unlock ac7f7b63d1d6e311695693235eb3262f60fea079 --password /root/payouts/password --verbosity 4
    volumes:
      - ./payouts:/root/payouts:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  ipfs:
    image: ipfs/go-ipfs
    command: daemon
    ports:
     - "8080:8080"
     - "5001:5001"
     - "4001:4001"
